spring:
  application:
    name: Secure-App
  datasource:
    url: ${DATABASE_URL_SECURE_APP}
    username: ${DATABASE_USERNAME_SECURE_APP}
    password: ${DATABASE_PASSWORD_SECURE_APP}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

springdoc:
  default-produces-media-type: application/json

server:
  tomcat:
    max-threads: 200
    accept-count: 100
